// 接口地址
export const BASE_URL = 'https://itf.kaxin.com'

// token
export const TOKEN_KEY = 'token'

// token_header
export const TOKEN_HEADER_KEY = 'token_header'

// preferences用户首选项
export const PREFERENCES_KEY = 'preference'

// 是否第一次启动
export const IS_LAUNCH_KEY = 'isLaunch'

// 用户信息
export const USER_INFO = 'userInfo'

// 登录信息
export const TOKEN_INFO = 'tokenInfo'

// config信息
export const CONFIG = 'config'

// SIP信息
export const SIP_DATA = 'sipData'

// 登录信息
export const LOGIN_INFO = 'loginInfo'

